
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ESCUCHAR = 13;
  public static final int NUMERO = 38;
  public static final int MULT = 19;
  public static final int PARENTESIS_CIERRA = 34;
  public static final int SI = 7;
  public static final int DIFERENTE = 22;
  public static final int RESTA = 18;
  public static final int ENTONCES = 9;
  public static final int FIN = 3;
  public static final int IDENTIFICADOR = 37;
  public static final int NOT = 29;
  public static final int AND = 27;
  public static final int RECORRER = 11;
  public static final int IGUAL = 21;
  public static final int OR = 28;
  public static final int MIENTRAS = 10;
  public static final int DIV = 20;
  public static final int SUMA = 17;
  public static final int GEO = 4;
  public static final int PUNTO_COMA = 31;
  public static final int EOF = 0;
  public static final int INVOCAR = 12;
  public static final int LUZ = 14;
  public static final int error = 1;
  public static final int COMA = 32;
  public static final int CADENA = 39;
  public static final int MENOR = 23;
  public static final int LLAVE_ABRE = 35;
  public static final int ASIGNACION = 30;
  public static final int MAYOR = 24;
  public static final int VACIO = 15;
  public static final int SOMBRA = 8;
  public static final int MAYOR_IGUAL = 26;
  public static final int ESENCIA = 6;
  public static final int LLAVE_CIERRA = 36;
  public static final int RETORNAR = 16;
  public static final int INICIO = 2;
  public static final int TEXTO = 5;
  public static final int MENOR_IGUAL = 25;
  public static final int PARENTESIS_ABRE = 33;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INICIO",
  "FIN",
  "GEO",
  "TEXTO",
  "ESENCIA",
  "SI",
  "SOMBRA",
  "ENTONCES",
  "MIENTRAS",
  "RECORRER",
  "INVOCAR",
  "ESCUCHAR",
  "LUZ",
  "VACIO",
  "RETORNAR",
  "SUMA",
  "RESTA",
  "MULT",
  "DIV",
  "IGUAL",
  "DIFERENTE",
  "MENOR",
  "MAYOR",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "AND",
  "OR",
  "NOT",
  "ASIGNACION",
  "PUNTO_COMA",
  "COMA",
  "PARENTESIS_ABRE",
  "PARENTESIS_CIERRA",
  "LLAVE_ABRE",
  "LLAVE_CIERRA",
  "IDENTIFICADOR",
  "NUMERO",
  "CADENA"
  };
}

